version: '3.8'

services:
  app:
    container_name: demo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    networks:
      - demo-network

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gksqja9691@
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: gksqja96912@
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - demo-network

volumes:
  mysql-data:

networks:
  demo-network:
