spring:
  profiles:
    default: local

  datasource:
    url: jdbc:mysql://mysql-db:3306/demo?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gksqja96912@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
